import type { CavAiPillar, CavAiTargetArea } from "./types";

export type CavAiEffortClass = "trivial" | "small" | "medium" | "large" | "major";

export type CavAiCodeDefinition = {
  code: string;
  label: string;
  pillar: CavAiPillar;
  effort: CavAiEffortClass;
  targetArea: CavAiTargetArea;
  whyItMatters: string;
  defaultAction: string;
};

export const CAVAI_CODE_CATALOG: Record<string, CavAiCodeDefinition> = {
  missing_title: {
    code: "missing_title",
    label: "Missing title tag",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Search and social previews lose relevance when pages do not ship titles.",
    defaultAction: "Add a deterministic title template for the affected routes.",
  },
  missing_meta_description: {
    code: "missing_meta_description",
    label: "Missing meta description",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Search snippets become weak and click intent drops.",
    defaultAction: "Define a per-template meta description fallback.",
  },
  missing_h1: {
    code: "missing_h1",
    label: "Missing H1",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Primary page intent becomes ambiguous for crawlers and assistive tools.",
    defaultAction: "Add exactly one H1 to the route template.",
  },
  multiple_h1: {
    code: "multiple_h1",
    label: "Multiple H1 elements",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Competing heading hierarchy makes route intent harder to resolve.",
    defaultAction: "Keep a single H1 and demote secondary headings.",
  },
  social_tags: {
    code: "social_tags",
    label: "Missing Open Graph/Twitter tags",
    pillar: "engagement",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Shared links lose context and lower preview conversion.",
    defaultAction: "Add Open Graph and Twitter metadata to shared templates.",
  },
  broken_links: {
    code: "broken_links",
    label: "Broken internal links",
    pillar: "ux",
    effort: "medium",
    targetArea: "content",
    whyItMatters: "Navigation trust erodes when users hit dead ends.",
    defaultAction: "Repair or remove links that resolve to non-success status.",
  },
  missing_alt: {
    code: "missing_alt",
    label: "Images missing alt text",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Screen readers lose the semantic meaning of visual content.",
    defaultAction: "Add meaningful alt text for all informative images.",
  },
  focus_visible: {
    code: "focus_visible",
    label: "Focus indicator not visible",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Keyboard users cannot track focus movement across controls.",
    defaultAction: "Apply consistent :focus-visible styling across interactive controls.",
  },
  missing_viewport: {
    code: "missing_viewport",
    label: "Missing viewport meta",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Mobile rendering quality and interaction sizing degrade without viewport settings.",
    defaultAction: "Add a stable viewport meta tag to the base template.",
  },
  missing_lang: {
    code: "missing_lang",
    label: "Missing document language",
    pillar: "accessibility",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Assistive technologies cannot reliably infer pronunciation rules.",
    defaultAction: "Set html lang for every locale variant.",
  },
  missing_canonical: {
    code: "missing_canonical",
    label: "Missing canonical URL",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Duplicate index candidates split ranking authority.",
    defaultAction: "Emit canonical links for template and dynamic routes.",
  },
  noindex: {
    code: "noindex",
    label: "Noindex present on indexable page",
    pillar: "seo",
    effort: "small",
    targetArea: "config",
    whyItMatters: "Critical pages can disappear from search discovery.",
    defaultAction: "Review robots directives for production routes.",
  },
  missing_favicon: {
    code: "missing_favicon",
    label: "Missing favicon",
    pillar: "seo",
    effort: "trivial",
    targetArea: "template",
    whyItMatters:
      "Browser tabs, bookmarks, and UI surfaces fall back to a generic icon which hurts trust and recognition.",
    defaultAction: "Add favicon assets and link tags in the shared head template.",
  },
  missing_apple_touch_icon: {
    code: "missing_apple_touch_icon",
    label: "Missing Apple touch icon",
    pillar: "seo",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "iOS home-screen saves lose branded icon quality without apple-touch metadata.",
    defaultAction: "Add a 180x180 apple-touch-icon link in the shared head template.",
  },
  missing_web_manifest_icon_set: {
    code: "missing_web_manifest_icon_set",
    label: "Missing web manifest icon set",
    pillar: "seo",
    effort: "small",
    targetArea: "config",
    whyItMatters: "Installability and PWA icon handling degrade without manifest icon definitions.",
    defaultAction: "Publish /site.webmanifest with 192x192 and 512x512 icon entries.",
  },
  theme_color_needs_branding: {
    code: "theme_color_needs_branding",
    label: "Theme color needs branding",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters:
      "Browser surfaces can appear generic or white when theme color metadata is missing or not brand-aligned.",
    defaultAction:
      "Set meta theme-color and align msapplication tile color to a brand-safe value.",
  },
  route_http_404: {
    code: "route_http_404",
    label: "404 route failures",
    pillar: "reliability",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Broken routes create navigation dead ends and support burden.",
    defaultAction: "Restore missing route handlers or update links to valid targets.",
  },
  route_http_5xx: {
    code: "route_http_5xx",
    label: "5xx route failures",
    pillar: "reliability",
    effort: "large",
    targetArea: "config",
    whyItMatters: "Server failures directly block user workflows and trust.",
    defaultAction: "Stabilize backend dependencies and route error handling.",
  },
  js_error_fingerprint: {
    code: "js_error_fingerprint",
    label: "Recurring JavaScript runtime error",
    pillar: "reliability",
    effort: "large",
    targetArea: "template",
    whyItMatters: "Runtime exceptions interrupt journeys and reduce conversion.",
    defaultAction: "Fix the repeated runtime fingerprint and verify crash-free recovery.",
  },
  api_error_cluster: {
    code: "api_error_cluster",
    label: "API failure cluster",
    pillar: "reliability",
    effort: "large",
    targetArea: "config",
    whyItMatters: "Critical backend operations are failing under real traffic.",
    defaultAction: "Address the API failure cluster root cause and add retries where safe.",
  },
  slow_response: {
    code: "slow_response",
    label: "Slow response times",
    pillar: "performance",
    effort: "medium",
    targetArea: "config",
    whyItMatters: "Perceived latency increases bounce and lowers task completion.",
    defaultAction: "Profile and optimize slow endpoints and render paths.",
  },
  high_lcp: {
    code: "high_lcp",
    label: "Large Contentful Paint regression",
    pillar: "performance",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Slow first impression reduces engagement and trust.",
    defaultAction: "Optimize critical rendering path and largest element loading.",
  },
  cls_shift: {
    code: "cls_shift",
    label: "Cumulative Layout Shift instability",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Unexpected layout movement causes interaction mistakes.",
    defaultAction: "Reserve layout space for async content and media.",
  },
  low_conversion_step: {
    code: "low_conversion_step",
    label: "Conversion funnel drop",
    pillar: "engagement",
    effort: "major",
    targetArea: "content",
    whyItMatters: "High-intent traffic is dropping before key completion steps.",
    defaultAction: "Review friction points and simplify the conversion step content.",
  },
  invalid_json_ld: {
    code: "invalid_json_ld",
    label: "Invalid JSON-LD block",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Malformed structured data is ignored by crawlers and blocks rich-result eligibility.",
    defaultAction: "Fix JSON syntax and validate each JSON-LD block against schema.org requirements.",
  },
  missing_structured_data: {
    code: "missing_structured_data",
    label: "Missing structured data",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Search engines lose deterministic context when schema.org metadata is absent.",
    defaultAction: "Add baseline Organization/WebSite JSON-LD graph in the shared head template.",
  },
  missing_website_schema: {
    code: "missing_website_schema",
    label: "Missing WebSite schema",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Website-level entity signals are incomplete for search understanding.",
    defaultAction: "Add WebSite node with stable @id and publisher relation.",
  },
  missing_organization_schema: {
    code: "missing_organization_schema",
    label: "Missing Organization schema",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Entity trust signals weaken without a canonical Organization node.",
    defaultAction: "Add Organization node using authenticated site identity settings.",
  },
  missing_person_schema: {
    code: "missing_person_schema",
    label: "Missing Person schema",
    pillar: "seo",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Personal profile sites need Person metadata for unambiguous authorship/entity mapping.",
    defaultAction: "Add Person schema node sourced from authenticated identity config.",
  },
  duplicate_json_ld_ids: {
    code: "duplicate_json_ld_ids",
    label: "Duplicate JSON-LD IDs",
    pillar: "seo",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Conflicting @id entities create ambiguous graph interpretations.",
    defaultAction: "Unify duplicate @id nodes so each identifier maps to one canonical entity definition.",
  },
  missing_softwareapp_fields: {
    code: "missing_softwareapp_fields",
    label: "SoftwareApplication fields missing",
    pillar: "seo",
    effort: "small",
    targetArea: "config",
    whyItMatters: "SoftwareApplication schema cannot be emitted safely without required identity/config fields.",
    defaultAction: "Complete SoftwareApplication fields in Site Identity configuration.",
  },
  missing_manifest: {
    code: "missing_manifest",
    label: "Missing web manifest",
    pillar: "seo",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Installability and icon metadata are incomplete when the manifest is missing.",
    defaultAction: "Add a manifest link and publish /site.webmanifest with 192x192 + 512x512 icons.",
  },
  missing_theme_color: {
    code: "missing_theme_color",
    label: "Missing theme color",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Browser surfaces lose branded polish without theme-color metadata.",
    defaultAction: "Add meta theme-color in the shared head template.",
  },
  missing_accessible_name: {
    code: "missing_accessible_name",
    label: "Missing accessible names",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Interactive controls become ambiguous for assistive technologies.",
    defaultAction: "Ensure all interactive controls expose accessible names via text, aria-label, or labelledby.",
  },
  missing_form_labels: {
    code: "missing_form_labels",
    label: "Missing form labels",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Unlabeled form inputs block screen-reader and keyboard comprehension.",
    defaultAction: "Associate every form control with a visible label and matching for/id pair.",
  },
  placeholder_as_label: {
    code: "placeholder_as_label",
    label: "Placeholder used as label",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Placeholder-only forms lose context once users type and often fail accessibility requirements.",
    defaultAction: "Add persistent labels and keep placeholder text as optional helper content.",
  },
  heading_level_skipped: {
    code: "heading_level_skipped",
    label: "Heading levels skipped",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Broken heading structure makes assistive navigation harder.",
    defaultAction: "Use ordered heading levels (H1 > H2 > H3) without skips.",
  },
  missing_main_landmark: {
    code: "missing_main_landmark",
    label: "Missing main landmark",
    pillar: "accessibility",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Landmark navigation is incomplete without a main region.",
    defaultAction: "Wrap primary content in <main> or role=\"main\".",
  },
  focus_outline_removed: {
    code: "focus_outline_removed",
    label: "Focus outline removed",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Keyboard users lose their navigation cursor without visible focus outlines.",
    defaultAction: "Restore :focus-visible outlines across all interactive elements.",
  },
  tabindex_misuse: {
    code: "tabindex_misuse",
    label: "Tabindex misuse",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Incorrect tabindex usage breaks predictable keyboard order.",
    defaultAction: "Remove positive tabindex values and rely on DOM order where possible.",
  },
  focus_trap_detected: {
    code: "focus_trap_detected",
    label: "Focus trap detected",
    pillar: "accessibility",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Users can get trapped in modal/UI regions and cannot continue workflows.",
    defaultAction: "Implement explicit modal focus management and escape paths.",
  },
  contrast_failure: {
    code: "contrast_failure",
    label: "Color contrast failure",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Low contrast text harms readability and can fail WCAG compliance.",
    defaultAction: "Adjust text/background colors to satisfy WCAG contrast thresholds.",
  },
  tap_target_too_small: {
    code: "tap_target_too_small",
    label: "Tap targets too small",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Small controls reduce touch usability and increase accidental taps.",
    defaultAction: "Increase target size to at least 44x44px.",
  },
  image_missing_alt: {
    code: "image_missing_alt",
    label: "Image alt text missing",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Screen readers cannot interpret informative imagery without alt text.",
    defaultAction: "Add concise alt text for informative images and empty alt for decorative ones.",
  },
  autoplay_audio_detected: {
    code: "autoplay_audio_detected",
    label: "Autoplay audio detected",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Autoplay audio surprises users and conflicts with accessibility expectations.",
    defaultAction: "Disable unmuted autoplay and require explicit user opt-in playback.",
  },
  media_controls_missing: {
    code: "media_controls_missing",
    label: "Media controls missing",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Users cannot start/stop media safely without controls.",
    defaultAction: "Enable native or equivalent accessible media controls.",
  },
  captions_track_missing: {
    code: "captions_track_missing",
    label: "Captions track missing",
    pillar: "accessibility",
    effort: "medium",
    targetArea: "content",
    whyItMatters: "Video content becomes inaccessible without caption tracks.",
    defaultAction: "Publish captions/subtitles for spoken media.",
  },
  reduced_motion_not_respected: {
    code: "reduced_motion_not_respected",
    label: "Reduced motion preference ignored",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Motion-sensitive users rely on prefers-reduced-motion accommodations.",
    defaultAction: "Respect prefers-reduced-motion and reduce/disable heavy animation.",
  },
  checkout_error_association_missing: {
    code: "checkout_error_association_missing",
    label: "Checkout error association missing",
    pillar: "accessibility",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Checkout errors become hard to resolve without explicit field-to-error associations.",
    defaultAction: "Wire checkout errors through aria-describedby and field error IDs.",
  },
  focus_error_summary_missing: {
    code: "focus_error_summary_missing",
    label: "Focus to error summary missing",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Failed submit states are harder to recover when focus is not moved to error summary.",
    defaultAction: "Move focus to top-level error summary after validation failure.",
  },
  product_image_alt_coverage_low: {
    code: "product_image_alt_coverage_low",
    label: "Product image alt coverage low",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Incomplete product alt text harms discoverability and accessibility.",
    defaultAction: "Backfill alt text for product imagery with deterministic naming rules.",
  },
  table_headers_missing: {
    code: "table_headers_missing",
    label: "Table headers missing",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Data tables become ambiguous without semantic headers.",
    defaultAction: "Use th elements and scope attributes for table headers.",
  },
  icon_button_missing_label: {
    code: "icon_button_missing_label",
    label: "Icon-only button missing label",
    pillar: "accessibility",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Icon-only controls need explicit labels for assistive technologies.",
    defaultAction: "Add aria-label/labelledby to icon-only buttons.",
  },
  modal_aria_missing: {
    code: "modal_aria_missing",
    label: "Modal ARIA semantics missing",
    pillar: "accessibility",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Dialogs without aria-modal/focus patterns degrade accessibility and navigation.",
    defaultAction: "Add role=\"dialog\"/aria-modal and deterministic focus trap + restore logic.",
  },
  chart_text_summary_missing: {
    code: "chart_text_summary_missing",
    label: "Chart text summary missing",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Charts require textual summaries for non-visual readers.",
    defaultAction: "Provide concise text summaries alongside charts.",
  },
  missing_custom_404_page: {
    code: "missing_custom_404_page",
    label: "Missing custom 404 page",
    pillar: "reliability",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Generic or absent 404 handling increases abandonment and support burden.",
    defaultAction: "Implement a branded 404 page with clear recovery actions.",
  },
  broken_404_nav_home: {
    code: "broken_404_nav_home",
    label: "404 home navigation missing",
    pillar: "reliability",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Users stranded on 404 pages need a direct path back home.",
    defaultAction: "Add keyboard-accessible Home navigation to the 404 template.",
  },
  internal_links_to_404: {
    code: "internal_links_to_404",
    label: "Internal links resolve to 404",
    pillar: "reliability",
    effort: "medium",
    targetArea: "content",
    whyItMatters: "Broken internal links create dead ends and hurt crawl/user trust.",
    defaultAction: "Repair or remove internal links pointing to not-found routes.",
  },
  status_404_misconfigured: {
    code: "status_404_misconfigured",
    label: "404 status misconfigured",
    pillar: "reliability",
    effort: "medium",
    targetArea: "config",
    whyItMatters: "Missing routes returning 200 hide errors from monitoring and crawlers.",
    defaultAction: "Return proper HTTP 404/410 for missing routes.",
  },
  missing_home_link: {
    code: "missing_home_link",
    label: "Missing home link in navigation",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Users lose an immediate recovery path when Home link is absent.",
    defaultAction: "Add a visible, accessible Home link in global navigation.",
  },
  missing_nav_landmark: {
    code: "missing_nav_landmark",
    label: "Missing navigation landmark",
    pillar: "accessibility",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Assistive users rely on navigation landmarks to move efficiently.",
    defaultAction: "Wrap primary nav in <nav> or role=\"navigation\".",
  },
  broken_back_to_top: {
    code: "broken_back_to_top",
    label: "Broken back-to-top control",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Long-page navigation degrades when back-to-top controls fail.",
    defaultAction: "Fix back-to-top anchor/button behavior and focus target.",
  },
  inconsistent_navigation: {
    code: "inconsistent_navigation",
    label: "Inconsistent navigation across pages",
    pillar: "ux",
    effort: "medium",
    targetArea: "template",
    whyItMatters: "Navigation drift across routes creates avoidable user confusion.",
    defaultAction: "Normalize global nav components across key templates.",
  },
  recommend_404_arcade_game: {
    code: "recommend_404_arcade_game",
    label: "Recommend 404 arcade module",
    pillar: "engagement",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Engaging 404 experiences can recover sessions and reduce bounce.",
    defaultAction: "Embed a deterministic 404 game module from the approved catalog.",
  },
  horizontal_overflow_detected: {
    code: "horizontal_overflow_detected",
    label: "Horizontal overflow detected",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Horizontal scrolling breaks layout integrity and mobile usability.",
    defaultAction: "Fix overflow-causing elements and constrain widths to viewport.",
  },
  viewport_meta_missing: {
    code: "viewport_meta_missing",
    label: "Viewport meta missing",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Mobile rendering quality degrades without a viewport directive.",
    defaultAction: "Add responsive viewport meta tag in the base head template.",
  },
  text_clip_overflow_risk: {
    code: "text_clip_overflow_risk",
    label: "Text clipping overflow risk",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Clipped headings/content can hide critical messaging and CTAs.",
    defaultAction: "Adjust overflow/text wrapping styles on clipping-prone elements.",
  },
  high_layout_shift: {
    code: "high_layout_shift",
    label: "High layout shift",
    pillar: "performance",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Layout shifts cause interaction errors and degrade trust.",
    defaultAction: "Reserve space for media/async blocks and stabilize initial layout.",
  },
  missing_loading_state: {
    code: "missing_loading_state",
    label: "Missing loading state",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Users perceive jumps and instability when loading states are absent.",
    defaultAction: "Add deterministic loading/skeleton states for delayed content.",
  },
  logo_missing_in_header: {
    code: "logo_missing_in_header",
    label: "Header logo missing",
    pillar: "ux",
    effort: "small",
    targetArea: "template",
    whyItMatters: "Missing logo weakens orientation and brand recognition.",
    defaultAction: "Place a consistent branded logo in the header across templates.",
  },
  logo_missing_alt: {
    code: "logo_missing_alt",
    label: "Header logo alt missing",
    pillar: "accessibility",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Logo images need alt text to convey destination/brand context.",
    defaultAction: "Add meaningful alt text for header logo image.",
  },
  logo_image_too_large: {
    code: "logo_image_too_large",
    label: "Header logo image too large",
    pillar: "performance",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Oversized logos increase transfer weight and hurt rendering speed.",
    defaultAction: "Compress/resize logo asset and ship responsive formats.",
  },
  missing_privacy_policy: {
    code: "missing_privacy_policy",
    label: "Missing privacy policy page",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Privacy transparency is a baseline trust signal for users and compliance.",
    defaultAction: "Publish a privacy policy page and expose it in global navigation/footer.",
  },
  missing_terms: {
    code: "missing_terms",
    label: "Missing terms page",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Terms coverage clarifies legal boundaries and purchase/service expectations.",
    defaultAction: "Publish Terms of Service and link it prominently.",
  },
  missing_contact_page: {
    code: "missing_contact_page",
    label: "Missing contact page",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Supportability trust drops when users cannot find a contact path.",
    defaultAction: "Add a contact page or direct contact channel in navigation/footer.",
  },
  missing_about_page: {
    code: "missing_about_page",
    label: "Missing about page",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "About pages provide core credibility context for new visitors.",
    defaultAction: "Publish an about page and link it from primary or footer navigation.",
  },
  missing_cookie_policy: {
    code: "missing_cookie_policy",
    label: "Missing cookie policy",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Cookie disclosures are required in many jurisdictions and improve trust.",
    defaultAction: "Publish cookie policy guidance for analytics/marketing cookies.",
  },
  missing_accessibility_statement: {
    code: "missing_accessibility_statement",
    label: "Missing accessibility statement",
    pillar: "accessibility",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Accessibility statements communicate commitment and support channels.",
    defaultAction: "Publish an accessibility statement and link it in footer or legal pages.",
  },
  missing_shipping_policy: {
    code: "missing_shipping_policy",
    label: "Missing shipping policy",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Ecommerce users need shipping expectations before checkout.",
    defaultAction: "Publish shipping policy and link it from checkout/footer.",
  },
  missing_returns_policy: {
    code: "missing_returns_policy",
    label: "Missing returns policy",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Return clarity is a major pre-purchase trust driver.",
    defaultAction: "Publish returns policy and keep it discoverable near product/checkout paths.",
  },
  missing_refund_policy: {
    code: "missing_refund_policy",
    label: "Missing refund policy",
    pillar: "ux",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Refund terms reduce checkout friction and support disputes.",
    defaultAction: "Publish refund policy with clear process and timelines.",
  },
  policy_not_linked_in_footer: {
    code: "policy_not_linked_in_footer",
    label: "Policy pages not linked in footer",
    pillar: "ux",
    effort: "trivial",
    targetArea: "template",
    whyItMatters: "Users expect legal/trust pages in footer navigation.",
    defaultAction: "Add policy/trust links to footer navigation on all templates.",
  },
  email_dns_not_checked: {
    code: "email_dns_not_checked",
    label: "Email DNS checks unavailable",
    pillar: "reliability",
    effort: "trivial",
    targetArea: "config",
    whyItMatters: "Email posture cannot be verified without SPF/DMARC DNS evidence.",
    defaultAction: "Run SPF/DMARC TXT checks from a network-enabled environment.",
  },
  missing_spf_record: {
    code: "missing_spf_record",
    label: "SPF TXT record missing",
    pillar: "reliability",
    effort: "small",
    targetArea: "config",
    whyItMatters: "Missing SPF weakens sender authentication posture.",
    defaultAction: "Publish SPF TXT record for outbound mail sources.",
  },
  missing_dmarc_record: {
    code: "missing_dmarc_record",
    label: "DMARC TXT record missing",
    pillar: "reliability",
    effort: "small",
    targetArea: "config",
    whyItMatters: "Missing DMARC prevents policy enforcement for spoofing protection.",
    defaultAction: "Publish DMARC TXT record with monitoring/enforcement policy.",
  },
  keyword_cluster_gap: {
    code: "keyword_cluster_gap",
    label: "Keyword topic cluster gap",
    pillar: "seo",
    effort: "small",
    targetArea: "content",
    whyItMatters: "Missing topic clusters reduce relevance breadth for target intents.",
    defaultAction: "Add profile-aligned topic coverage in titles, headings, and supporting content.",
  },
  keywords_insufficient_data: {
    code: "keywords_insufficient_data",
    label: "Keyword data insufficient",
    pillar: "seo",
    effort: "trivial",
    targetArea: "config",
    whyItMatters: "Keyword extraction cannot run reliably when source signals are missing.",
    defaultAction: "Provide stable title/meta/heading signals and rerun deterministic extraction.",
  },
  auth_login_failure_spike: {
    code: "auth_login_failure_spike",
    label: "Login failure spike",
    pillar: "reliability",
    effort: "medium",
    targetArea: "config",
    whyItMatters: "Login failure spikes block user access and can indicate regressions.",
    defaultAction: "Review auth failures by status bucket and top error fingerprints.",
  },
  signup_failure_spike: {
    code: "signup_failure_spike",
    label: "Signup failure spike",
    pillar: "reliability",
    effort: "medium",
    targetArea: "config",
    whyItMatters: "Signup failures reduce growth and indicate onboarding friction.",
    defaultAction: "Audit signup validation/runtime errors and restore conversion path.",
  },
  auth_endpoint_error_cluster: {
    code: "auth_endpoint_error_cluster",
    label: "Auth endpoint error cluster",
    pillar: "reliability",
    effort: "large",
    targetArea: "config",
    whyItMatters: "Repeated auth endpoint fingerprints indicate systemic reliability risk.",
    defaultAction: "Triage the dominant auth error fingerprint and patch root causes.",
  },
  geo_distribution_shift: {
    code: "geo_distribution_shift",
    label: "Geo distribution shift",
    pillar: "engagement",
    effort: "small",
    targetArea: "config",
    whyItMatters: "Large geo distribution shifts can indicate acquisition or delivery changes.",
    defaultAction: "Review geo trend deltas and adjust localization/performance strategy as needed.",
  },
};

const FALLBACK_DEFINITION: CavAiCodeDefinition = {
  code: "unknown",
  label: "Unmapped deterministic finding",
  pillar: "reliability",
  effort: "medium",
  targetArea: "config",
  whyItMatters: "A deterministic signal requires review and explicit ownership.",
  defaultAction: "Triage the signal and assign a stable remediation plan.",
};

export function resolveCodeDefinition(
  code: string,
  fallbackPillar: CavAiPillar
): CavAiCodeDefinition {
  const normalized = String(code || "").trim().toLowerCase();
  const existing = CAVAI_CODE_CATALOG[normalized];
  if (existing) return existing;
  return {
    ...FALLBACK_DEFINITION,
    code: normalized || FALLBACK_DEFINITION.code,
    pillar: fallbackPillar,
    label: normalized ? `Unmapped code: ${normalized}` : FALLBACK_DEFINITION.label,
  };
}

export function knownCodeSet() {
  return new Set(Object.keys(CAVAI_CODE_CATALOG));
}
