CREATE TYPE "AuditCategory" AS ENUM ('sites', 'keys', 'system', 'changes');
CREATE TYPE "AuditSeverity" AS ENUM ('info', 'warning', 'destructive');

ALTER TABLE "AuditLog" ADD COLUMN "actionLabel" TEXT NOT NULL DEFAULT '';
ALTER TABLE "AuditLog" ADD COLUMN "category" "AuditCategory" NOT NULL DEFAULT 'system';
ALTER TABLE "AuditLog" ADD COLUMN "severity" "AuditSeverity" NOT NULL DEFAULT 'info';
ALTER TABLE "AuditLog" ADD COLUMN "targetLabel" TEXT;

CREATE INDEX "AuditLog_category_idx" ON "AuditLog"("category");

ALTER TYPE "AuditAction" ADD VALUE 'ACCOUNT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_2FA_EMAIL_SENT';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_LOGIN_FAILED';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_SIGNED_IN';
ALTER TYPE "AuditAction" ADD VALUE 'AUTH_SIGNED_OUT';
ALTER TYPE "AuditAction" ADD VALUE 'BILLING_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'EMAIL_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'MEMBER_ROLE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'PASSWORD_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'PLAN_DOWNGRADED';
ALTER TYPE "AuditAction" ADD VALUE 'PLAN_UPGRADED';
ALTER TYPE "AuditAction" ADD VALUE 'PROFILE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'RETENTION_WINDOW_EXPIRED';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_DELETED_IMMEDIATE';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_DETACHED';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_PURGE_EXECUTED';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_PURGE_SCHEDULED';
ALTER TYPE "AuditAction" ADD VALUE 'SITE_RESTORED';
ALTER TYPE "AuditAction" ADD VALUE 'SYSTEM_JOB_RAN';
