export type AgentModeKey = "caven" | "cavai" | "companion";
export type AgentCategory =
  | "mode_feature"
  | "hidden_system"
  | "caven_native"
  | "cavai_work"
  | "companion_only";
export type AgentBank = "none" | "caven_native" | "cavai_work" | "companion";
export type AgentVisibility = "visible" | "hidden_system" | "hidden_mode_feature";
export type AgentPlanTier = "free" | "premium" | "premium_plus";
export type AgentSurface = "cavcode" | "center" | "all";
export type AgentCenterMode = "general" | "companion";

export type AgentCatalogEntry = {
  id: string;
  name: string;
  slug: string;
  summary: string;
  iconSrc: string;
  actionKey: string;
  cavcodeAction: string | null;
  centerAction: string | null;
  category: AgentCategory;
  bank: AgentBank;
  visibility: AgentVisibility;
  planTier: AgentPlanTier;
  installable: boolean;
  hiddenSystem: boolean;
  availableToModes: AgentModeKey[];
  sharedWithCaven: boolean;
  sharedWithCavai: boolean;
  sharedWithCompanion: boolean;
  supportForCaven: boolean;
  surface: AgentSurface;
  mode: AgentCenterMode;
  defaultInstalled: boolean;
  displayOrder: number;
};

function entry(def: AgentCatalogEntry): AgentCatalogEntry {
  return def;
}

export const AGENT_CATALOG: AgentCatalogEntry[] = [
  entry({
    id: "cavai_auto",
    name: "CavAi Auto",
    slug: "cavai-auto",
    summary: "Model-selection mode.",
    iconSrc: "",
    actionKey: "cavai_auto",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 1,
  }),
  entry({
    id: "deepseek_chat",
    name: "DeepSeek Chat",
    slug: "deepseek-chat",
    summary: "Model option.",
    iconSrc: "",
    actionKey: "deepseek_chat",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 2,
  }),
  entry({
    id: "deepseek_reasoner",
    name: "DeepSeek Reasoner",
    slug: "deepseek-reasoner",
    summary: "Model option.",
    iconSrc: "",
    actionKey: "deepseek_reasoner",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 3,
  }),
  entry({
    id: "qwen35_flash",
    name: "Qwen3.5-Flash",
    slug: "qwen3-5-flash",
    summary: "Model option.",
    iconSrc: "",
    actionKey: "qwen35_flash",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["cavai", "companion"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 4,
  }),
  entry({
    id: "qwen35_plus",
    name: "Qwen3.5-Plus",
    slug: "qwen3-5-plus",
    summary: "Model option.",
    iconSrc: "",
    actionKey: "qwen35_plus",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 5,
  }),
  entry({
    id: "qwen3_max",
    name: "Qwen3-Max",
    slug: "qwen3-max",
    summary: "Model option.",
    iconSrc: "",
    actionKey: "qwen3_max",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 6,
  }),
  entry({
    id: "caven_mode",
    name: "Caven",
    slug: "caven",
    summary: "Product mode.",
    iconSrc: "",
    actionKey: "caven_mode",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 7,
  }),
  entry({
    id: "cavbot_companion_mode",
    name: "CavBot Companion",
    slug: "cavbot-companion",
    summary: "Product mode.",
    iconSrc: "",
    actionKey: "cavbot_companion_mode",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "companion",
    defaultInstalled: false,
    displayOrder: 8,
  }),
  entry({
    id: "dictate_voice_input",
    name: "Dictate / voice input",
    slug: "dictate-voice-input",
    summary: "Feature.",
    iconSrc: "",
    actionKey: "dictate_voice_input",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 9,
  }),
  entry({
    id: "image_studio_feature",
    name: "Image Studio",
    slug: "image-studio",
    summary: "Feature.",
    iconSrc: "",
    actionKey: "image_studio_feature",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 10,
  }),
  entry({
    id: "image_edit_feature",
    name: "Image Edit",
    slug: "image-edit",
    summary: "Feature.",
    iconSrc: "",
    actionKey: "image_edit_feature",
    cavcodeAction: null,
    centerAction: null,
    category: "mode_feature",
    bank: "none",
    visibility: "hidden_mode_feature",
    planTier: "free",
    installable: false,
    hiddenSystem: false,
    availableToModes: ["caven", "cavai"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 11,
  }),

  entry({
    id: "knowledge_grounding_curator",
    name: "Knowledge Grounding Agent",
    slug: "knowledge-grounding-agent",
    summary: "Hidden system grounding layer.",
    iconSrc: "/icons/app/deep-learning-svgrepo-com.svg",
    actionKey: "knowledge_grounding",
    cavcodeAction: null,
    centerAction: "web_research",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 20,
  }),
  entry({
    id: "deterministic_research_planner",
    name: "Deterministic Research Planner",
    slug: "deterministic-research-planner",
    summary: "Hidden system planning layer.",
    iconSrc: "/icons/app/research-svgrepo-com.svg",
    actionKey: "deterministic_research",
    cavcodeAction: null,
    centerAction: "web_research",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 21,
  }),
  entry({
    id: "citation_only_answerer",
    name: "Citation-Only Answerer",
    slug: "citation-only-answerer",
    summary: "Hidden system citation layer.",
    iconSrc: "/icons/app/block-quote-svgrepo-com.svg",
    actionKey: "citation_only_answer",
    cavcodeAction: null,
    centerAction: "web_research",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 22,
  }),
  entry({
    id: "prompt_compiler",
    name: "Prompt Compiler",
    slug: "prompt-compiler",
    summary: "Hidden system prompt compiler.",
    iconSrc: "/icons/cavpad/sparkles-svgrepo-com.svg",
    actionKey: "compile_prompt",
    cavcodeAction: null,
    centerAction: "bullets_to_plan",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 23,
  }),
  entry({
    id: "memory_curator",
    name: "Memory Curator",
    slug: "memory-curator",
    summary: "Hidden system memory layer.",
    iconSrc: "/icons/app/memory-svgrepo-com.svg",
    actionKey: "curate_memory",
    cavcodeAction: null,
    centerAction: "summarize_thread",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 24,
  }),
  entry({
    id: "grounding_gap_detector",
    name: "Grounding Gap Detector",
    slug: "grounding-gap-detector",
    summary: "Hidden system grounding QA.",
    iconSrc: "/icons/app/grid-3x3-gap-fill-svgrepo-com.svg",
    actionKey: "detect_grounding_gaps",
    cavcodeAction: null,
    centerAction: "web_research",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 25,
  }),
  entry({
    id: "execution_critic",
    name: "Execution Critic",
    slug: "execution-critic",
    summary: "Hidden system execution QA.",
    iconSrc: "/icons/app/operation-and-maintenance-center-execution-record-svgrepo-com.svg",
    actionKey: "critique_execution",
    cavcodeAction: null,
    centerAction: "technical_recap",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 26,
  }),
  entry({
    id: "spec_to_tasks_orchestrator",
    name: "Spec-to-Tasks Orchestrator",
    slug: "spec-to-tasks-orchestrator",
    summary: "Hidden system orchestration layer.",
    iconSrc: "/icons/app/graph-bar-svgrepo-com.svg",
    actionKey: "orchestrate_spec_tasks",
    cavcodeAction: null,
    centerAction: "bullets_to_plan",
    category: "hidden_system",
    bank: "none",
    visibility: "hidden_system",
    planTier: "premium",
    installable: false,
    hiddenSystem: true,
    availableToModes: ["caven", "cavai", "companion"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "all",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 27,
  }),

  entry({
    id: "error_explainer",
    name: "Error Explainer",
    slug: "error-explainer",
    summary: "Break down compiler and runtime errors into plain language with likely causes.",
    iconSrc: "/icons/app/alert-caution-error-svgrepo-com.svg",
    actionKey: "explain_error",
    cavcodeAction: "explain_error",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 100,
  }),
  entry({
    id: "fix_draft",
    name: "Fix Draft",
    slug: "fix-draft",
    summary: "Generate an initial patch proposal for a bug with low-risk defaults.",
    iconSrc: "/icons/app/cavcode/agents/repairing-browser-svgrepo-com.svg",
    actionKey: "suggest_fix",
    cavcodeAction: "suggest_fix",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 101,
  }),
  entry({
    id: "safe_refactor",
    name: "Safe Refactor",
    slug: "safe-refactor",
    summary: "Refactor code while preserving behavior and reducing accidental regressions.",
    iconSrc: "/icons/app/cavcode/agents/security-priority-svgrepo-com.svg",
    actionKey: "refactor_safely",
    cavcodeAction: "refactor_safely",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 102,
  }),
  entry({
    id: "code_explainer",
    name: "Code Explainer",
    slug: "code-explainer",
    summary: "Explain complex files and call flows quickly for onboarding and review.",
    iconSrc: "/icons/app/cavcode/agents/compile-compiler-script-code-config-svgrepo-com.svg",
    actionKey: "explain_code",
    cavcodeAction: "explain_code",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 103,
  }),
  entry({
    id: "file_summarizer",
    name: "File Summarizer",
    slug: "file-summarizer",
    summary: "Summarize large files into concise technical notes and key takeaways.",
    iconSrc: "/icons/app/cavcode/agents/note-favorite-svgrepo-com.svg",
    actionKey: "summarize_file",
    cavcodeAction: "summarize_file",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 104,
  }),
  entry({
    id: "component_builder",
    name: "Component Builder",
    slug: "component-builder",
    summary: "Generate reusable UI components with consistent structure and naming.",
    iconSrc: "/icons/app/cavcode/agents/web-application-svgrepo-com.svg",
    actionKey: "generate_component",
    cavcodeAction: "generate_component",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 105,
  }),
  entry({
    id: "section_builder",
    name: "Section Builder",
    slug: "section-builder",
    summary: "Draft complete page sections from intent, content, and layout direction.",
    iconSrc: "/icons/app/cavcode/agents/window-section-svgrepo-com.svg",
    actionKey: "generate_section",
    cavcodeAction: "generate_section",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 106,
  }),
  entry({
    id: "page_builder",
    name: "Page Builder",
    slug: "page-builder",
    summary: "Generate full page scaffolds with coherent structure and implementation hints.",
    iconSrc: "/icons/app/cavcode/agents/page-builder-clean.svg",
    actionKey: "generate_page",
    cavcodeAction: "generate_page",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 107,
  }),
  entry({
    id: "engineering_note",
    name: "Engineering Note",
    slug: "engineering-note",
    summary: "Write clean changelogs, technical notes, and implementation summaries.",
    iconSrc: "/icons/app/cavcode/agents/engineering-svgrepo-com.svg",
    actionKey: "write_note",
    cavcodeAction: "write_note",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 108,
  }),
  entry({
    id: "page_404_builder_agent",
    name: "404 Builder",
    slug: "404-page-builder-agent",
    summary: "Build 404 route content and page structure for polished not-found UX.",
    iconSrc: "/icons/link-broken-svgrepo-com.svg",
    actionKey: "page_404_builder_agent",
    cavcodeAction: "page_404_builder_agent",
    centerAction: "page_404_builder_agent",
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: true,
    displayOrder: 109,
  }),
  entry({
    id: "app_screenshot_enhancer",
    name: "App Screenshot Enhancer",
    slug: "app-screenshot-enhancer",
    summary: "Enhance product screenshots into marketing-ready visuals with advanced image editing.",
    iconSrc: "/icons/app/screenshot-2-svgrepo-com.svg",
    actionKey: "app_screenshot_enhancer",
    cavcodeAction: "app_screenshot_enhancer",
    centerAction: "image_edit",
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "premium_plus",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 110,
  }),
  entry({
    id: "ui_debug_visualizer",
    name: "UI Debug Visualizer",
    slug: "ui-debug-visualizer",
    summary: "Visualize expected UI states and suggest practical code fixes for layout mismatches.",
    iconSrc: "/icons/app/bug-fix-search-virus-debug-find-svgrepo-com.svg",
    actionKey: "ui_debug_visualizer",
    cavcodeAction: "ui_debug_visualizer",
    centerAction: "image_studio",
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "premium_plus",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 111,
  }),
  entry({
    id: "api_schema_contract_guard",
    name: "API Schema Contract Guard",
    slug: "api-schema-contract-guard",
    summary: "Validate changes against API and schema contracts before execution and rollout.",
    iconSrc: "/icons/app/api-app-svgrepo-com.svg",
    actionKey: "guard_api_contracts",
    cavcodeAction: "api_schema_contract_guard",
    centerAction: null,
    category: "caven_native",
    bank: "caven_native",
    visibility: "visible",
    planTier: "premium_plus",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["caven"],
    sharedWithCaven: true,
    sharedWithCavai: false,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "cavcode",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 112,
  }),

  entry({
    id: "seo_improver",
    name: "SEO Improver",
    slug: "seo-improver",
    summary: "Improve metadata, headings, and content structure for search discoverability.",
    iconSrc: "/icons/app/cavcode/agents/seo-svgrepo-com.svg",
    actionKey: "improve_seo",
    cavcodeAction: "improve_seo",
    centerAction: "technical_recap",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 200,
  }),
  entry({
    id: "competitor_intelligence",
    name: "Competitor Intelligence",
    slug: "competitor-intelligence",
    summary: "Research competitor products, positioning, pricing, and feature gaps with evidence-first comparisons.",
    iconSrc: "/icons/app/chart-bubble-svgrepo-com.svg",
    actionKey: "competitor_research",
    cavcodeAction: "competitor_research",
    centerAction: "web_research",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 201,
  }),
  entry({
    id: "accessibility_auditor",
    name: "Accessibility Auditor",
    slug: "accessibility-auditor",
    summary: "Audit code for WCAG and a11y risks, then propose practical remediation steps and patches.",
    iconSrc: "/icons/app/cavcode/agents/accessibility-svgrepo-com.svg",
    actionKey: "accessibility_audit",
    cavcodeAction: "accessibility_audit",
    centerAction: "technical_recap",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 202,
  }),
  entry({
    id: "ui_mockup_generator",
    name: "UI Mockup Generator",
    slug: "ui-mockup-generator",
    summary: "Generate UI mockups with paired implementation code for websites and apps.",
    iconSrc: "/icons/app/atom-ai-svgrepo-com.svg",
    actionKey: "ui_mockup_generator",
    cavcodeAction: "ui_mockup_generator",
    centerAction: "image_studio",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "premium",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 203,
  }),
  entry({
    id: "website_visual_builder",
    name: "Website Visual Builder",
    slug: "website-visual-builder",
    summary: "Create website-ready visual assets and variants for pages, features, and campaigns.",
    iconSrc: "/icons/app/wireframe-svgrepo-com.svg",
    actionKey: "website_visual_builder",
    cavcodeAction: "website_visual_builder",
    centerAction: "image_studio",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "premium",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 204,
  }),
  entry({
    id: "brand_asset_generator",
    name: "Brand Asset Generator",
    slug: "brand-asset-generator",
    summary: "Generate branded icons, banners, and campaign visuals aligned with your product identity.",
    iconSrc: "/icons/app/star-rings-svgrepo-com.svg",
    actionKey: "brand_asset_generator",
    cavcodeAction: "brand_asset_generator",
    centerAction: "image_studio",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "premium",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 205,
  }),
  entry({
    id: "email_text_agent",
    name: "Messenger",
    slug: "email-text-agent",
    summary: "Draft and rewrite messages with flexible professional or personal tone.",
    iconSrc: "/icons/smartphone-2-svgrepo-com.svg",
    actionKey: "email_text_agent",
    cavcodeAction: "email_text_agent",
    centerAction: "email_text_agent",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 206,
  }),
  entry({
    id: "content_creator",
    name: "Content Creator",
    slug: "content-creator",
    summary: "Generate titles, sections, and structured website or campaign copy blocks.",
    iconSrc: "/icons/app/aperture-svgrepo-com.svg",
    actionKey: "content_creator",
    cavcodeAction: "content_creator",
    centerAction: "content_creator",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 207,
  }),
  entry({
    id: "legal_privacy_terms_ethics_agent",
    name: "Counsel",
    slug: "legal-privacy-terms-ethics-agent",
    summary: "Draft policy and terms-style language with compliance-oriented framing.",
    iconSrc: "/icons/legal-hammer-symbol-svgrepo-com.svg",
    actionKey: "legal_privacy_terms_ethics_agent",
    cavcodeAction: "legal_privacy_terms_ethics_agent",
    centerAction: "legal_privacy_terms_ethics_agent",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "premium",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 208,
  }),
  entry({
    id: "pdf_create_edit_preview_agent",
    name: "PDF Studio",
    slug: "pdf-create-edit-preview-agent",
    summary: "Create, refine, and preview PDF outputs for clean document workflows.",
    iconSrc: "/icons/pdf-file-svgrepo-com.svg",
    actionKey: "pdf_create_edit_preview_agent",
    cavcodeAction: "pdf_create_edit_preview_agent",
    centerAction: "pdf_create_edit_preview_agent",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "premium",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 209,
  }),
  entry({
    id: "doc_edit_review_agent",
    name: "Doc Review",
    slug: "doc-file-edit-review-agent",
    summary: "Review, edit, and restructure documents for clarity and quality.",
    iconSrc: "/icons/doc-on-doc-fill-svgrepo-com.svg",
    actionKey: "doc_edit_review_agent",
    cavcodeAction: "doc_edit_review_agent",
    centerAction: "doc_edit_review_agent",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 210,
  }),
  entry({
    id: "web_research_analyst",
    name: "Web Research Analyst",
    slug: "web-research-analyst",
    summary: "Synthesize external signals into actionable insights for technical decisions.",
    iconSrc: "/icons/app/connection-svgrepo-com.svg",
    actionKey: "web_research",
    cavcodeAction: "web_research",
    centerAction: "web_research",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 211,
  }),
  entry({
    id: "incident_analyst",
    name: "Incident Analyst",
    slug: "incident-analyst",
    summary: "Digest issue spikes and produce prioritized incident response recommendations.",
    iconSrc: "/icons/app/cavcode/agents/alert-symbol-svgrepo-com.svg",
    actionKey: "summarize_issues",
    cavcodeAction: "summarize_issues",
    centerAction: "summarize_issues",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 212,
  }),
  entry({
    id: "storage_organizer",
    name: "Storage Organizer",
    slug: "storage-organizer",
    summary: "Recommend cleaner folder structures and artifact organization patterns.",
    iconSrc: "/icons/app/storage-svgrepo-com.svg",
    actionKey: "organize_storage",
    cavcodeAction: "organize_storage",
    centerAction: "organize_storage",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai"],
    sharedWithCaven: false,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: false,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 213,
  }),
  entry({
    id: "access_auditor",
    name: "Access Auditor",
    slug: "access-auditor",
    summary: "Explain access constraints and flag risky sharing or permission gaps.",
    iconSrc: "/icons/app/cavcode/agents/grapheneos-auditor-svgrepo-com.svg",
    actionKey: "audit_access_context",
    cavcodeAction: "audit_access_context",
    centerAction: "audit_access_context",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 214,
  }),
  entry({
    id: "thread_summarizer",
    name: "Thread Summarizer",
    slug: "thread-summarizer",
    summary: "Condense long threads into clear summaries and rewrite drafts for clarity.",
    iconSrc: "/icons/app/cavcode/agents/message-basic-app-conversation-chat-svgrepo-com.svg",
    actionKey: "summarize_thread",
    cavcodeAction: "summarize_thread",
    centerAction: "summarize_thread",
    category: "cavai_work",
    bank: "cavai_work",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["cavai", "caven"],
    sharedWithCaven: true,
    sharedWithCavai: true,
    sharedWithCompanion: false,
    supportForCaven: true,
    surface: "center",
    mode: "general",
    defaultInstalled: false,
    displayOrder: 215,
  }),

  entry({
    id: "financial_advisor",
    name: "Financial Advisor",
    slug: "financial-advisor",
    summary: "Clarify budgeting, tradeoffs, and money decisions with practical planning support.",
    iconSrc: "/icons/finance-symbol-of-four-currencies-on-a-hand-svgrepo-com.svg",
    actionKey: "financial_advisor",
    cavcodeAction: null,
    centerAction: "financial_advisor",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 300,
  }),
  entry({
    id: "therapist_support",
    name: "Therapist Support",
    slug: "therapist-support",
    summary: "Offer reflective grounding and emotional processing support without clinical claims.",
    iconSrc: "/icons/friend-svgrepo-com.svg",
    actionKey: "therapist_support",
    cavcodeAction: null,
    centerAction: "therapist_support",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 301,
  }),
  entry({
    id: "mentor",
    name: "Mentor",
    slug: "mentor",
    summary: "Drive disciplined growth with direct guidance on next moves and long-term direction.",
    iconSrc: "/icons/person-svgrepo-com.svg",
    actionKey: "mentor",
    cavcodeAction: null,
    centerAction: "mentor",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 302,
  }),
  entry({
    id: "best_friend",
    name: "Best Friend",
    slug: "best-friend",
    summary: "Bring warm perspective, encouragement, and honest support in daily decision-making.",
    iconSrc: "/icons/teddy-bear-with-heart-svgrepo-com.svg",
    actionKey: "best_friend",
    cavcodeAction: null,
    centerAction: "best_friend",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 303,
  }),
  entry({
    id: "relationship_advisor",
    name: "Relationship Advisor",
    slug: "relationship-advisor",
    summary: "Help frame communication and conflict with balanced emotional perspective.",
    iconSrc: "/icons/relationship-counseling-marriage-counseling-couples-therapy-marriage-therapy-svgrepo-com.svg",
    actionKey: "relationship_advisor",
    cavcodeAction: null,
    centerAction: "relationship_advisor",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 304,
  }),
  entry({
    id: "philosopher",
    name: "Philosopher",
    slug: "philosopher",
    summary: "Expand perspective with deeper framing on meaning, values, and direction.",
    iconSrc: "/icons/priest-2-svgrepo-com.svg",
    actionKey: "philosopher",
    cavcodeAction: null,
    centerAction: "philosopher",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 305,
  }),
  entry({
    id: "focus_coach",
    name: "Focus Coach",
    slug: "focus-coach",
    summary: "Reduce overwhelm, prioritize clearly, and convert intent into immediate execution.",
    iconSrc: "/icons/focus-svgrepo-com.svg",
    actionKey: "focus_coach",
    cavcodeAction: null,
    centerAction: "focus_coach",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 306,
  }),
  entry({
    id: "life_strategist",
    name: "Life Strategist",
    slug: "life-strategist",
    summary: "Connect life goals and work goals with practical sequencing and action clarity.",
    iconSrc: "/icons/achievement-2-svgrepo-com.svg",
    actionKey: "life_strategist",
    cavcodeAction: null,
    centerAction: "life_strategist",
    category: "companion_only",
    bank: "companion",
    visibility: "visible",
    planTier: "free",
    installable: true,
    hiddenSystem: false,
    availableToModes: ["companion"],
    sharedWithCaven: false,
    sharedWithCavai: false,
    sharedWithCompanion: true,
    supportForCaven: false,
    surface: "center",
    mode: "companion",
    defaultInstalled: true,
    displayOrder: 307,
  }),
];

export const AGENT_CATALOG_BY_ID = new Map<string, AgentCatalogEntry>(AGENT_CATALOG.map((row) => [row.id, row]));

export const INSTALLABLE_AGENT_CATALOG = AGENT_CATALOG
  .filter((row) => row.installable && row.visibility === "visible")
  .sort((a, b) => a.displayOrder - b.displayOrder);

export const INSTALLABLE_AGENT_ID_SET = new Set<string>(INSTALLABLE_AGENT_CATALOG.map((row) => row.id));

export const DEFAULT_INSTALLED_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.defaultInstalled)
  .map((row) => row.id);

export const CAVEN_NATIVE_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.bank === "caven_native")
  .map((row) => row.id);

export const CAVAI_WORK_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.bank === "cavai_work")
  .map((row) => row.id);

export const COMPANION_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.bank === "companion")
  .map((row) => row.id);

export const CAVEN_SUPPORT_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.supportForCaven)
  .map((row) => row.id);

export const CAVEN_PREMIUM_PLUS_LOCKED_AGENT_IDS = INSTALLABLE_AGENT_CATALOG
  .filter((row) => row.bank === "caven_native" && row.planTier === "premium_plus")
  .map((row) => row.id);

export const HIDDEN_SYSTEM_AGENT_IDS = AGENT_CATALOG
  .filter((row) => row.hiddenSystem)
  .map((row) => row.id);

export function planTierRank(tier: AgentPlanTier): number {
  if (tier === "premium_plus") return 3;
  if (tier === "premium") return 2;
  return 1;
}

export function isAgentPlanEligible(agentPlanTier: AgentPlanTier, accountPlanTier: AgentPlanTier): boolean {
  return planTierRank(accountPlanTier) >= planTierRank(agentPlanTier);
}

export function normalizeAgentPlanTier(value: unknown): AgentPlanTier {
  const raw = String(value || "").trim().toLowerCase();
  if (raw === "premium_plus" || raw === "premium+") return "premium_plus";
  if (raw === "premium") return "premium";
  return "free";
}

export function sortAgentsByDisplayOrder<T extends { id: string }>(rows: T[]): T[] {
  return [...rows].sort((a, b) => {
    const orderA = AGENT_CATALOG_BY_ID.get(a.id)?.displayOrder ?? Number.MAX_SAFE_INTEGER;
    const orderB = AGENT_CATALOG_BY_ID.get(b.id)?.displayOrder ?? Number.MAX_SAFE_INTEGER;
    return orderA - orderB;
  });
}
