export const CAVSAFE_NOTIFICATION_KINDS = {
  SAFE_STORAGE_LOW_80: "SAFE_STORAGE_LOW_80",
  SAFE_STORAGE_LOW_95: "SAFE_STORAGE_LOW_95",
  SAFE_UPLOAD_FAILED: "SAFE_UPLOAD_FAILED",
  SAFE_MOVE_FAILED: "SAFE_MOVE_FAILED",
  SAFE_EVIDENCE_PUBLISHED: "SAFE_EVIDENCE_PUBLISHED",
  SAFE_SNAPSHOT_CREATED: "SAFE_SNAPSHOT_CREATED",
  SAFE_TIMELOCK_EVENT: "SAFE_TIMELOCK_EVENT",
  SAFE_INVITE: "SAFE_INVITE",
  SAFE_INVITE_ACCEPTED: "SAFE_INVITE_ACCEPTED",
  SAFE_ACCESS_REVOKED: "SAFE_ACCESS_REVOKED",
} as const;

export const CAVCLOUD_NOTIFICATION_KINDS = {
  CLOUD_STORAGE_LOW_80: "CLOUD_STORAGE_LOW_80",
  CLOUD_STORAGE_LOW_95: "CLOUD_STORAGE_LOW_95",
  CLOUD_UPLOAD_FAILED: "CLOUD_UPLOAD_FAILED",
  CLOUD_SHARE_EXPIRING_SOON: "CLOUD_SHARE_EXPIRING_SOON",
  CLOUD_ARTIFACT_PUBLISHED: "CLOUD_ARTIFACT_PUBLISHED",
  CLOUD_ARTIFACT_UNPUBLISHED: "CLOUD_ARTIFACT_UNPUBLISHED",
  CLOUD_PURGE_COMPLETED: "CLOUD_PURGE_COMPLETED",
  CLOUD_COLLAB_REQUEST_CREATED: "CLOUD_COLLAB_REQUEST_CREATED",
  CLOUD_COLLAB_REQUEST_APPROVED: "CLOUD_COLLAB_REQUEST_APPROVED",
  CLOUD_COLLAB_REQUEST_DENIED: "CLOUD_COLLAB_REQUEST_DENIED",
  CLOUD_COLLAB_ACCESS_GRANTED: "CLOUD_COLLAB_ACCESS_GRANTED",
  CLOUD_COLLAB_ACCESS_REVOKED: "CLOUD_COLLAB_ACCESS_REVOKED",
  FILE_SHARED_TO_YOU: "FILE_SHARED_TO_YOU",
  FOLDER_SHARED_TO_YOU: "FOLDER_SHARED_TO_YOU",
  CLOUD_FILE_EDIT_CONFLICT: "CLOUD_FILE_EDIT_CONFLICT",
  CLOUD_FILE_EDIT_DENIED: "CLOUD_FILE_EDIT_DENIED",
  CLOUD_CONTRIBUTOR_LINK_CREATED: "CLOUD_CONTRIBUTOR_LINK_CREATED",
  CLOUD_CONTRIBUTOR_LINK_USED: "CLOUD_CONTRIBUTOR_LINK_USED",
  CLOUD_CONTRIBUTOR_LINK_DENIED: "CLOUD_CONTRIBUTOR_LINK_DENIED",
} as const;

export const WORKSPACE_NOTIFICATION_KINDS = {
  WORKSPACE_INVITE_RECEIVED: "WORKSPACE_INVITE_RECEIVED",
  WORKSPACE_ACCESS_REQUEST_RECEIVED: "ACCESS_REQUEST_RECEIVED",
  WORKSPACE_INVITE_ACCEPTED: "WORKSPACE_INVITE_ACCEPTED",
  WORKSPACE_ACCESS_REQUEST_APPROVED: "ACCESS_REQUEST_APPROVED",
  WORKSPACE_ACCESS_REQUEST_DENIED: "ACCESS_REQUEST_DENIED",
  WORKSPACE_INVITE_DECLINED: "WORKSPACE_INVITE_DECLINED",
  ACCESS_REQUEST_RECEIVED: "ACCESS_REQUEST_RECEIVED",
  ACCESS_REQUEST_APPROVED: "ACCESS_REQUEST_APPROVED",
} as const;

export type CavSafeNotificationKind =
  (typeof CAVSAFE_NOTIFICATION_KINDS)[keyof typeof CAVSAFE_NOTIFICATION_KINDS];

export type CavCloudNotificationKind =
  (typeof CAVCLOUD_NOTIFICATION_KINDS)[keyof typeof CAVCLOUD_NOTIFICATION_KINDS];

export type WorkspaceNotificationKind =
  (typeof WORKSPACE_NOTIFICATION_KINDS)[keyof typeof WORKSPACE_NOTIFICATION_KINDS];

export type NotificationKind =
  | CavSafeNotificationKind
  | CavCloudNotificationKind
  | WorkspaceNotificationKind
  | "GENERIC";
