ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FILE_UPLOADED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FILE_RENAMED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FILE_DELETED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FOLDER_MOVED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'ARTIFACT_PUBLISHED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'COLLAB_GRANTED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'COLLAB_REVOKED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'ACCESS_GRANTED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'ACCESS_REVOKED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FILE_OPENED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FILE_DOWNLOADED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'EDIT_SAVED';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'EDIT_CONFLICT';
ALTER TYPE "CavCloudOperationKind" ADD VALUE IF NOT EXISTS 'FAILED_EDIT_ATTEMPT';

ALTER TABLE "CavCloudCollabPolicy"
ADD COLUMN IF NOT EXISTS "allowAdminsViewAccessLogs" BOOLEAN NOT NULL DEFAULT false;
